# Generated by Django 4.1.2 on 2023-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_encoding',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
